spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db:3306/appdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8}
    username: ${SPRING_DATASOURCE_ROOT_USERNAME:root}
    password: ${SPRING_DATASOURCE_ROOT_PASSWORD:rootpass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: false

server:
  port: ${SERVER_PORT:8081}
  forward-headers-strategy: native
  error: # evita el uso de BasicErrorController para poder usar WebErrorController
    whitelabel:
      enabled: false
services:
  py1:
    url: ${PY1_BASE_URL:http://py1:5000}
  py2:
    url: ${PY2_BASE_URL:http://py2:5000}
    items-url: ${services.py2.url}/items # Valor para Items service (necesitado por Sonar)

depends_on:
  backend:
    condition: service_healthy
  py1:
    condition: service_healthy
  py2:
    condition: service_healthy

app:
  backendBaseUrl: ${BACKEND_BASE_URL:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: health, info